### ISSUE TITLE
lineEnding in console mode adds an extra \n

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/sallust#26]
When using console mode, the line ending appears to default to a `\n` but the encoder also then appends a default `\n` so you end up with double spaced lines.

Setting the following makes the default value of `\n` active again:
```
  level: debug
  development: true
  encoding: console
  encoderConfig:
    lineEnding: ""
```
